name: locarb_attendance
description: LoCarb Attendance (Web + Mobile) - MVP full skeleton
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.2
  firebase_messaging: ^15.0.3

  # Utils
  provider: ^6.1.2
  geolocator: ^13.0.1
  file_picker: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
